In [1]:
import pandas as pd

In [2]:
a = pd.read_csv('students.csv')
b = pd.read_csv('sub.csv')

In [6]:
a.head()

,child_id,target,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15
0,ID_00603FMFS,61.962040,teacher_emotional_total,child_height,ses_proxy,child_observe_total,teacher_emotional_total_pri_fees_amount_pv_mul...,teacher_emotional_total_pri_fees_amount_multiply,child_zha,child_observe_diligent,pri_fees_amount,child_dob_month,child_observe_total_mean_enum,child_observe_total_mean,child_observe_attentive,pri_fees_amount_pv_pri_fees_amount_multiply,child_observe_concentrated
1,ID_006AP9OS1,44.129148,child_observe_diligent,child_dob_month,child_observe_total,child_observe_attentive,child_age_mean,child_age_std_enum,child_date_day_mean_enum,count_register_year_2020,child_observe_concentrated,teacher_emotional_understand,teacher_social_total_mean_enum,obs_materials_12,child_age_std,quintile_std_enum,quintile_std
2,ID_00WATQ5BZ,44.026666,child_height,latitude_longitude_divide,child_observe_diligent,child_zha,child_observe_total,child_observe_attentive,pri_funding_subsidy_mean_enum,child_years_in_programme,child_dob_month,child_age_std_enum,child_age_mean,teacher_emotional_understand,count_register_year_2020,pra_agency_understand,longitude
3,ID_01C33S7YN,48.977375,teacher_emotional_total,child_age,teacher_emotional_total_pri_fees_amount_multiply,count_staff_qual_nqf6_9_std_enum,pra_measure_rectangle_width_std_prov,child_observe_total_std,count_staff_all_std_prov,teacher_emotional_total_pri_fees_amount_pv_mul...,teacher_social_total,child_age_mean,child_age_child_height_divide,child_observe_total_mean,id_facility,child_observe_total_mean_enum,count_register_year_2020
4,ID_01RAL2DTR,44.983090,pri_fees_amount_std_enum,child_observe_total_mean_enum,child_observe_attentive,pri_fees_amount_pv_std,child_observe_total_mean,count_register_race_other_std_enum,child_zha,count_register_gender_male_std_enum,id_ward_mean,count_register_race_std_enum,loc_group,pri_fees_amount_std,count_staff_time_full_std_enum,teacher_selfcare_total_std,teacher_emotional_understand

In [7]:
b.head()

,child_id,target,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15
0,ID_00603FMFS,59.814503,target_encode,child_observe_totalc_mean_x1000,teacher_emotional_total_x10,child_age_child_height_multiply_x10,child_zha_x10,child_age_x1000,child_observe_totalc_mean_x10,teacher_social_total_x1000,child_age_child_height_divide_x10,child_age_child_height_multiply_x1000,child_dob_day_x10,child_date_month_x1000,child_age_freq,child_date_day_x10,child_agec_std_x10
1,ID_006AP9OS1,44.137751,target_encode,child_observe_totalc_mean_x1000,teacher_emotional_total_x10,child_age_child_height_multiply_x10,child_zha_x10,child_age_x1000,child_observe_totalc_mean_x10,child_age_child_height_divide_x10,child_age_child_height_multiply_x1000,child_dob_day_x10,child_date_month_x1000,child_age_freq,child_date_day_x10,child_agec_std_x10,ses_proxy_x1000
2,ID_00WATQ5BZ,46.694614,target_encode,child_observe_totalc_mean_x1000,teacher_emotional_total_x10,child_age_child_height_multiply_x10,child_zha_x10,child_age_x1000,child_observe_totalc_mean_x10,child_age_child_height_divide_x10,child_age_child_height_multiply_x1000,child_dob_day_x10,child_date_month_x1000,child_age_freq,child_date_day_x10,child_agec_std_x10,ses_proxy_x1000
3,ID_01C33S7YN,46.885931,target_encode,child_observe_totalc_mean_x1000,teacher_emotional_total_x10,child_age_child_height_multiply_x10,child_zha_x10,child_age_x1000,child_observe_totalc_mean_x10,teacher_social_total_x1000,child_age_child_height_divide_x10,child_age_child_height_multiply_x1000,child_dob_day_x10,child_date_month_x1000,child_age_freq,child_date_day_x10,child_agec_std_x10
4,ID_01RAL2DTR,44.310727,target_encode,child_observe_totalc_mean_x1000,teacher_emotional_total_x10,child_age_child_height_multiply_x10,child_zha_x10,child_age_x1000,child_observe_totalc_mean_x10,teacher_social_total_x1000,child_age_child_height_divide_x10,child_age_child_height_multiply_x1000,child_dob_day_x10,child_date_month_x1000,child_age_freq,child_date_day_x10,child_agec_std_x10

In [5]:
a = a.sort_values(by='child_id').reset_index(drop=True)
b = b.sort_values(by='child_id').reset_index(drop=True)

In [9]:
a['target'].corr(b['target'])

0.9752318927365656

In [10]:
a['target'] = a['target']*0.7 + b['target']*0.3

In [11]:
a.head()

,child_id,target,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15
0,ID_00603FMFS,61.317779,teacher_emotional_total,child_height,ses_proxy,child_observe_total,teacher_emotional_total_pri_fees_amount_pv_mul...,teacher_emotional_total_pri_fees_amount_multiply,child_zha,child_observe_diligent,pri_fees_amount,child_dob_month,child_observe_total_mean_enum,child_observe_total_mean,child_observe_attentive,pri_fees_amount_pv_pri_fees_amount_multiply,child_observe_concentrated
1,ID_006AP9OS1,44.131729,child_observe_diligent,child_dob_month,child_observe_total,child_observe_attentive,child_age_mean,child_age_std_enum,child_date_day_mean_enum,count_register_year_2020,child_observe_concentrated,teacher_emotional_understand,teacher_social_total_mean_enum,obs_materials_12,child_age_std,quintile_std_enum,quintile_std
2,ID_00WATQ5BZ,44.827050,child_height,latitude_longitude_divide,child_observe_diligent,child_zha,child_observe_total,child_observe_attentive,pri_funding_subsidy_mean_enum,child_years_in_programme,child_dob_month,child_age_std_enum,child_age_mean,teacher_emotional_understand,count_register_year_2020,pra_agency_understand,longitude
3,ID_01C33S7YN,48.349942,teacher_emotional_total,child_age,teacher_emotional_total_pri_fees_amount_multiply,count_staff_qual_nqf6_9_std_enum,pra_measure_rectangle_width_std_prov,child_observe_total_std,count_staff_all_std_prov,teacher_emotional_total_pri_fees_amount_pv_mul...,teacher_social_total,child_age_mean,child_age_child_height_divide,child_observe_total_mean,id_facility,child_observe_total_mean_enum,count_register_year_2020
4,ID_01RAL2DTR,44.781381,pri_fees_amount_std_enum,child_observe_total_mean_enum,child_observe_attentive,pri_fees_amount_pv_std,child_observe_total_mean,count_register_race_other_std_enum,child_zha,count_register_gender_male_std_enum,id_ward_mean,count_register_race_std_enum,loc_group,pri_fees_amount_std,count_staff_time_full_std_enum,teacher_selfcare_total_std,teacher_emotional_understand

In [12]:
a.to_csv('ade_caleb_ensemble.csv', index=False)